pipeline {
   agent any
   tools{
       jdk 'JDK1.8'
       maven 'Maven3'
   }
   options {
       timestamps()
       buildDiscarder(logRotator(artifactDaysToKeepStr: '10', artifactNumToKeepStr: '10', daysToKeepStr: '10', numToKeepStr: '10'))
   }
 stages {
     stage ('Display PATH of Jenkins'){
         steps {
             sh '''
             echo "This is Declarative pipeline for building ServiceApp"
             echo "PATH = ${PATH}"
             '''
         }
     }
     stage ('Checkout the Source Code') {
        steps {
        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'f06c68d4-7b33-4388-8d34-ec01f4bc7a85', url: 'https://github.com/ysrgithub/serviceapp-pipe.git']]])        }
    }
      stage ('Building the Souce using Maven') {
          steps {
              sh 'mvn clean compile install'
          }
      }
      stage ('Archive artifacts for ServiceApp'){
          steps{
              archiveArtifacts '**/**/*.war'
          }
      }
    }
}

